/* 
 * File:   main.cpp
 * Author: Colleen Carleton
 * Created on January 10, 2017, 12:45 PM
 * Purpose:  Program to calculate the income generated by selling Class A, 
 * Class B, and Class C seats at a stadium.
 */

//System Libraries Here
#include <iostream>
#include <iomanip>
using namespace std;

//User Libraries Here

//Global Constants Only, No Global Variables
//Like PI, e, Gravity, or conversions

//Function Prototypes Here

//Program Execution Begins Here
int main(int argc, char** argv) {
    //Declare all Variables Here
    int seatsCA, seatsCB, seatsCC, costCA=15, costCB=12, costCC=9, totalCA, totalCB, totalCC, income;
    
    //Input or initialize values Here
    cout<<"This program will calculate the income generated by selling Class A, Class B, and Class C seats"<<endl;
    cout<<"Enter the number of Class A seats sold"<<endl;
    cin>>seatsCA;
    cout<<"Enter the number of Class B seats sold"<<endl;
    cin>>seatsCB;
    cout<<"Enter the number of Class C seats sold"<<endl;
    cin>>seatsCC;
    
    //Process/Calculations Here
    totalCA=seatsCA*costCA;
    totalCB=seatsCB*costCB;
    totalCC=seatsCC*costCC;
    income=totalCA+totalCB+totalCC;
    
    //Output Located Here
    cout<<setprecision(2)<<fixed<<showpoint;
    cout<<"Income from Class A seats was $"<<totalCA<<endl;
    cout<<"Income from Class B seats was $"<<totalCB<<endl;
    cout<<"Income from Class C seats was $"<<totalCC<<endl;
    cout<<"Total income was $"<<income<<endl;

    //Exit
    return 0;
}

